name: mobile_services
description: Mobile Services for SAP Product
version: 0.0.1
homepage: https://github.com/mobui/mobile_services


environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner: ^2.1.5

flutter:

